apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  dnsNames:
  - 'example.com'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
