apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
spec:
  hosts:
  {{- range .Values.hostname }}
  - {{ . }}
  {{- end }}
  gateways:
  - {{ .Values.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.name }}
        port:
          number: {{ .Values.service.port }}

