apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: infra
spec:
  version: 7.6.0
  nodeSets:
  - name: elasticsearch
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: infra
      spec:
        storageClassName: elasticsearch-data
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  namespace: infra
spec:
  capacity:
    storage: 50Gi
  storageClassName: elasticsearch-data
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.4.1
    path: /srv/nfsroot/elasticsearch

