kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.storage }}

