apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: internal-service
  labels:
    name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: tutum/dnsutils
    command:
    - sleep
    - "3600"
