replicaCount: 1

image:
  repo: requarks/wiki:2.1.113
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

name: wiki
hostname: 
  - "wiki.im-neko.net"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  # Annotations applied for services such as externalDNS or
  # service type LoadBalancer
  # type: LoadBalancer
  # httpsPort: 443
  # annotations: {}

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

db:
  type: mariadb
  host: mariadb.infra.svc.cluster.local
  secretName: wiki-secret
  name: db_name
  user: db_user
  pass: db_pass
  port: "3306"


nodeSelector: {}

tolerations: []

affinity: {}
